- ignore: {name: "Redundant ^."}
- ignore: {name: "Eta reduce"}
- ignore: {name: "Avoid lambda"}
- ignore: {name: "Use newtype instead of data"}
- ignore: {name: "Use tuple-section"}
- ignore: {name: "Use <$>"}
- ignore: {name: "Avoid lambda using `infix`"}
