name: Linting

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  fourmolu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/run-fourmolu@v10
      with:
        version: "0.14.1.0"
        pattern: |
          boreal-client/**/*.hs
          boreal-api/**/*.hs 
          boreal-daemon/app/**/*.hs
          boreal-daemon/compiler/**/*.hs 
          boreal-daemon/test/BorealTest/**/*.hs
          boreal-daemon/test/*.hs 

  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.6.1'

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: '["boreal-client", "boreal-api", "boreal-daemon/app", "boreal-daemon/compiler", "boreal-daemon/test/BorealTest", "boreal-daemon/test/Main.hs", "boreal-daemon/test/Utils.hs"]'
        fail-on: warning
