name: Linting

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  fourmolu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/run-fourmolu@v10
      with:
        version: "0.14.1.0"
        pattern: |
          compiler/**/*.hs
          test/**/*.hs

  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.6.1'

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: '["compiler/", "test/"]'
        fail-on: warning
